version: '3'
services:
  web:
    build: .
    command: pnpm dev
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rbac
    ports:
      - '5432:5432'
